name: CI/CD Pipeline for .NET Core App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore DotNetCoreApp/DotNetCoreApp.csproj  # Specify the path to the project file

    - name: Build the project
      run: dotnet build DotNetCoreApp/DotNetCoreApp.csproj --configuration Release  # Specify the path to the project file

    - name: Run tests
      run: dotnet test DotNetCoreApp.Tests/DotNetCoreApp.Tests.csproj --configuration Release  # Specify the test project file

  sonarQubeAnalysis:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SonarQube scanner
      uses: sonarsource/sonarcloud-github-action@v1
      with:
        projectBaseDir: '.'  # Set base directory to current working directory if needed

    - name: Run SonarQube analysis
      run: |
        dotnet sonarscanner begin /k:"github-actions-learning_cicd" /d:sonar.login=${{ secrets.SONAR_TOKEN }}
    
    - name: Build the project for analysis
      run: dotnet build --configuration Release
    
    - name: End SonarQube analysis
      run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}

