name: CI/CD Pipeline for .NET Core App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Install SonarScanner .NET Core Global Tool
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Restore dependencies
      run: dotnet restore DotNetCoreApp/DotNetCoreApp.csproj

    - name: Build the project
      run: dotnet build DotNetCoreApp/DotNetCoreApp.csproj --configuration Release

    - name: Run tests
      run: dotnet test DotNetCoreApp.Tests/DotNetCoreApp.Tests.csproj --configuration Release

  sonarQubeAnalysis:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SonarScanner .NET Core Global Tool
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Run SonarQube analysis
      run: |
        dotnet sonarscanner begin /o:"aneeshdasmazumder" /k:"aneeshdasmazumder_cicd-dotnet" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.token=${{ secrets.SONAR_TOKEN }}
    
    - name: Build the project for analysis
      run: dotnet build --configuration Release

    - name: End SonarQube analysis
      run: dotnet sonarscanner end /d:sonar.token=${{ secrets.SONAR_TOKEN }}
