name: CI/CD Pipeline for .NET Core App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore DotNetCoreApp/DotNetCoreApp.csproj  # Specify the path to the project file

    - name: Build the project
      run: dotnet build DotNetCoreApp/DotNetCoreApp.csproj --configuration Release  # Specify the path to the project file

    - name: Run tests
      run: dotnet test DotNetCoreApp.Tests/DotNetCoreApp.Tests.csproj --configuration Release  # Specify the test project file
